openapi: 3.0.0
info:
  title: KLIPS Heat Island Results API
  description: This API is part of the [KLIPS project](http://www.klips-projekt.de/) and accepts results about the urban heat islands simulation and prediction.
  version: 0.1.0
  host: klips-dev.terrestris.de
  basePath: /api
  schemes:
    - https
servers:
  - url: https://klips-dev.terrestris.de/api

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
security:
  - basicAuth: []
paths:
  /status:
    get:
      summary: Information about the status of the API
      security:
        - basicAuth: []
      responses:
        200:
          description: OK
        401:
           $ref: '#/components/responses/UnauthorizedError'
  /job:
    post:
      summary: Submit a new result about a heat island in GeoTIFF format
      produces:
        - application/json
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              title: Information about the new result
              type: object
              properties:
                source:
                  type: string
                  description: The name of the submitting institution
                email:
                  type: string
                  description: The email to send error reports to
                payload:
                  type: object
                  description: The information about the new result
                  properties:
                    url:
                      type: string
                      description: The URL where to download the result GeoTIFF from
                    creationTime:
                      type: integer
                      description: The creation time as ISO8601 string
                    predictionStartTime:
                      type: integer
                      description: The start time of the prediction as ISO8601 string
                    predictionEndTime:
                      type: integer
                      description: The end time of the prediction as ISO8601 string
                    interval:
                      type: integer
                      description: The interval in seconds
                    region:
                      type: string
                      description: The region name
                    scenario:
                      type: string
                      description: The scenario of the result
                  required:
                      - url
                      - creationTime
                      - predictionStartTime
                      - predictionEndTime
                      - interval
                      - region
                      - scenario
              required:
                - source
                - email
                - payload
              example:
                email: info@example.de
                payload:
                  url: https://klips-dev.terrestris.de/cog/dresden/dresden_temperature/20220216T1146Z.tif
                  creationTime: "2022-10-07T12:32:33.004Z"
                  predictionStartTime: "2022-10-08T12:32:33.004Z"
                  predictionEndTime: "2022-10-09T12:32:33.004Z"
                  interval: 3600
                  region: "dresden"
                  scenario: "forecast"
                source: hhi

      responses:
        200:
          description: OK
        401:
           $ref: '#/components/responses/UnauthorizedError'
