server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: ${PYGEOAPI_BASEURL}
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en
        - de
    cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: INFO

metadata:
    identification:
        title:
            en: KLIPS pygeoapi instance
        description:
            en: KLIPS pygeoapi instance
        keywords:
            en:
                - geospatial
                - data
                - api
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:

    zonal-statistics-grass:
        type: process
        processor:
            name: processes.zonal_statistics_grass.ZonalStatisticsGrassProcessor

    location-info-rasterstats:
        type: process
        processor:
            name: processes.location_info_rasterstats.LocationInfoRasterstatsProcessor

    location-info-time-rasterstats:
        type: process
        processor:
            name: processes.location_info_time_rasterstats.LocationInfoTimeRasterstatsProcessor

    zonal-statistics-rasterstats:
        type: process
        processor:
            name: processes.zonal_statistics_rasterstats.ZonalStatisticsRasterstatsProcessor

    zonal-statistics-time-rasterstats:
        type: process
        processor:
            name: processes.zonal_statistics_time_rasterstats.ZonalStatisticsTimeRasterstatsProcessor

    timelapse-video:
        type: process
        processor:
            name: processes.timelapse_video.TimelapseVideoProcessor
    
    contour-polygons:
        type: process
        processor:
            name: processes.contour_polygons.ContourPolygonsProcessor
    
    contour-polygons-time:
        type: process
        processor:
            name: processes.contour_polygons_time.ContourPolygonsTimeProcessor
