name: Create and publish the 'geoserver-init' Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%dT%H%M')"

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./geoserver-init
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/geoserver-init:latest
            ghcr.io/${{ github.repository_owner }}/geoserver-init:${{ steps.timestamp.outputs.timestamp }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./pygeoapi
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pygeoapi:latest
            ghcr.io/${{ github.repository_owner }}/pygeoapi:${{ steps.timestamp.outputs.timestamp }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./worker/error-handler
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mqm-worker/error-handler:latest
            ghcr.io/${{ github.repository_owner }}/mqm-worker/error-handler:${{ steps.timestamp.outputs.timestamp }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./worker/rollback-handler
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mqm-worker/rollback-handler:latest
            ghcr.io/${{ github.repository_owner }}/mqm-worker/rollback-handler:${{ steps.timestamp.outputs.timestamp }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./geoserver
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/geoserver:latest
            ghcr.io/${{ github.repository_owner }}/geoserver:${{ steps.timestamp.outputs.timestamp }}
