name: Deploy on Server

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: trigger deploy script
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }} 'sh /home/${{ secrets.SSH_USER }}/klips-sdi/deploy.sh'
