name: Lint geoserver-init files
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: set -e
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install and Lint
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - run: cd geoserver-init && npm ci
      - run: cd geoserver-init && npm run lint
