name: Lint and test pygeoapi files
on:
  push:
    branches:
      - fix-pipeline
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install program "wait-for-it"
        run: sudo apt install wait-for-it
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black rio-cogeo rasterstats
      - name: Ensures job is exited on error
        run: set -e
      - name: Provide a .env file for running the docker-compose setup
        run: cp .env.example .env
      # - name: Run NGINX from docker-compose setup to create a dummy webspace for the test
      #   run: docker-compose -f docker-compose.yml up -d nginx
      - name: start dummy nginx on port 81
        run: docker run -d -p 81:80 nginx
      - name: Wait until dummy webspace is available
        run: wait-for-it "localhost:81"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Python files
        run: bash dev_scripts/lint.sh
        working-directory: pygeoapi
      - name: Test Python files
        run: bash dev_scripts/test.sh
        working-directory: pygeoapi
